<a href="https://colab.research.google.com/github/gabrielycarrari/tcc/blob/pre-processing/pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook para Pré-processamento

# Importações

In [1]:
!pip install datasets
from datasets import load_dataset

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 kB 769.3 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.3/474.3 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 kB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 18.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 11.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.5/239.5 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.6/124.6 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 446.8/446.8 kB 22.3 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.9.0
    Uninstalling fsspec-2024.9.0:
      Successfully uninstalled fsspec-2024.9.0


In [13]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
from huggingface_hub import login
from google.colab import userdata


In [3]:
login(token=userdata.get('HUGGINGFACE_TOKEN'))

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [4]:
# Carregar o dataset Common Voice 17
dataset = load_dataset("mozilla-foundation/common_voice_17_0", "pt", split='train', trust_remote_code=True)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


common_voice_17_0.py:   0%|          | 0.00/8.19k [00:00<?, ?B/s]

README.md:   0%|          | 0.00/12.7k [00:00<?, ?B/s]

languages.py:   0%|          | 0.00/3.92k [00:00<?, ?B/s]

release_stats.py:   0%|          | 0.00/132k [00:00<?, ?B/s]

n_shards.json:   0%|          | 0.00/17.5k [00:00<?, ?B/s]

pt_train_0.tar:   0%|          | 0.00/627M [00:00<?, ?B/s]

pt_dev_0.tar:   0%|          | 0.00/291M [00:00<?, ?B/s]

pt_test_0.tar:   0%|          | 0.00/306M [00:00<?, ?B/s]

pt_other_0.tar:   0%|          | 0.00/666M [00:00<?, ?B/s]

pt_invalidated_0.tar:   0%|          | 0.00/229M [00:00<?, ?B/s]

pt_validated_0.tar:   0%|          | 0.00/1.21G [00:00<?, ?B/s]

pt_validated_1.tar:   0%|          | 0.00/1.14G [00:00<?, ?B/s]

pt_validated_2.tar:   0%|          | 0.00/1.06G [00:00<?, ?B/s]

pt_validated_3.tar:   0%|          | 0.00/851M [00:00<?, ?B/s]

transcript/pt/train.tsv:   0%|          | 0.00/6.68M [00:00<?, ?B/s]

transcript/pt/dev.tsv:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

transcript/pt/test.tsv:   0%|          | 0.00/2.70M [00:00<?, ?B/s]

transcript/pt/other.tsv:   0%|          | 0.00/7.69M [00:00<?, ?B/s]

transcript/pt/invalidated.tsv:   0%|          | 0.00/2.26M [00:00<?, ?B/s]

validated.tsv:   0%|          | 0.00/47.1M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]


Reading metadata...: 0it [00:00, ?it/s]
Reading metadata...: 21968it [00:00, 159197.19it/s]


Generating validation split: 0 examples [00:00, ? examples/s]


Reading metadata...: 9464it [00:00, 174576.67it/s]


Generating test split: 0 examples [00:00, ? examples/s]


Reading metadata...: 9467it [00:00, 172265.96it/s]


Generating other split: 0 examples [00:00, ? examples/s]


Reading metadata...: 0it [00:00, ?it/s]
Reading metadata...: 24946it [00:00, 163482.27it/s]


Generating invalidated split: 0 examples [00:00, ? examples/s]


Reading metadata...: 7307it [00:00, 163661.69it/s]


Generating validated split: 0 examples [00:00, ? examples/s]


Reading metadata...: 0it [00:00, ?it/s]
Reading metadata...: 17019it [00:00, 170182.86it/s]
Reading metadata...: 34038it [00:00, 165443.87it/s]
Reading metadata...: 50592it [00:00, 159549.16it/s]
Reading metadata...: 66568it [00:00, 157454.97it/s]
Reading metadata...: 82325it [00:00, 152342.21it/s]
Reading metadata...: 97581it [00:00, 148597.87it/s]
Reading metadata...: 112459it [00:00, 146176.26it/s]
Reading metadata...: 127087it [00:00, 144685.65it/s]
Reading metadata...: 152647it [00:01, 148161.02it/s]


### Testes

In [6]:
dataset

Dataset({
    features: ['client_id', 'path', 'audio', 'sentence', 'up_votes', 'down_votes', 'age', 'gender', 'accent', 'locale', 'segment', 'variant'],
    num_rows: 21968
})

In [32]:
dataset[0]['sentence']

'Sinta-se feliz com a vitória que você ganha.'

In [20]:
file = tf.io.read_file('/content/samples_pt_sample.wav')

In [34]:
import librosa
import tensorflow as tf
import soundfile as sf

# Load the audio file with librosa
audio_data, sample_rate = librosa.load('/content/samples_pt_sample.wav', sr=None)

# Resample to 16kHz (if necessary)
target_sample_rate = 16000
if sample_rate != target_sample_rate:
    audio_data = librosa.resample(audio_data, orig_sr=sample_rate, target_sr=target_sample_rate)

# Save the resampled audio as a WAV file
sf.write('resampled_audio.wav', audio_data, target_sample_rate)

# Load the resampled file using tensorflow
file = tf.io.read_file('resampled_audio.wav')
audio, _ = tf.audio.decode_wav(file)

In [35]:
audio = tf.squeeze(audio, axis=-1)
# 3. Change type to float
audio = tf.cast(audio, tf.float32)

In [36]:
audio

<tf.Tensor: shape=(74240,), dtype=float32, numpy=
array([2.2583008e-03, 2.4719238e-03, 1.5869141e-03, ..., 3.0517578e-05,
       9.1552734e-05, 9.1552734e-05], dtype=float32)>

In [37]:
audio2 = dataset[0]['audio']['array']
sampling_rate = dataset[0]['audio']['sampling_rate']

# 2. Convert audio to a tensor
audio2 = tf.convert_to_tensor(audio2, dtype=tf.float32)

In [40]:
dataset[0]['audio']['sampling_rate']

48000

In [38]:
audio2

<tf.Tensor: shape=(195264,), dtype=float32, numpy=
array([ 1.7763568e-15, -5.4178884e-14, -9.0594199e-14, ...,
        1.7286314e-10,  1.4505579e-10,  7.1001274e-11], dtype=float32)>

### Definindo Caracteres

In [10]:
# The set of characters accepted in the transcription.
characters = [x for x in "abcdefghijklmnopqrstuvwxyzáàâãéêíóôõúç'?!.- "]

# Mapping characters to integers
char_to_num = keras.layers.StringLookup(vocabulary=characters, oov_token="")

# Mapping integers back to original characters
num_to_char = keras.layers.StringLookup(
    vocabulary=char_to_num.get_vocabulary(), oov_token="", invert=True
)

print(
    f"The vocabulary is: {char_to_num.get_vocabulary()} "
    f"(size={char_to_num.vocabulary_size()})"
)

The vocabulary is: ['', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'á', 'à', 'â', 'ã', 'é', 'ê', 'í', 'ó', 'ô', 'õ', 'ú', 'ç', "'", '?', '!', '.', '-', ' '] (size =45)


# Data Preprocessing

In [11]:
# The window length in samples.
frame_length = 256
# The number of samples to step.
frame_step = 160
# The size of the FFT to apply.
fft_length = 384